import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const isLocal = process.env.NODE_ENV === "development";
const backgroundImagePath = isLocal ? "/bg.jpg" : "/bg.jpg";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        {/* ドラッグアイコン */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20,300,0,0&icon_names=drag_indicator"
        />
      </head>
      <body
        className={`relative antialiased h-screen select-none overflow-hidden`}
      >
        {/* <Image
          src={backgroundImagePath}
          alt="background"
          layout="fill"
          className="absolute h-full w-full z-[-10] object-contain"
        /> */}
        {children}
      </body>
    </html>
  );
}
